const fs = require('fs');
const path = require('path');
const enDir = path.join(process.cwd(), 'src/data/blog/en');
if (!fs.existsSync(enDir)) fs.mkdirSync(enDir, { recursive: true });

const posts = {
  'girls-names-list.json': {
    title: 'Kurdish Girls Names and Meanings (Most Beautiful and Unheard)',
    desc: 'Discover the most beautiful, modern, and unique Kurdish girl names and meanings. A wonderful guide to inspire you when choosing a name for your baby.',
    content: `Kurdish culture, with its rich history and language, contains very naive, poetic, and deeply meaningful names for girls. If you are looking for Kurdish girl names for your newborn baby, you are in the right place. We have compiled the most beautiful, popular, and unheard Kurdish girl names from traditional to modern.\n\n## Popular Kurdish Girl Names\n\nFor parents expecting a baby girl, choosing a name is undoubtedly one of the most researched topics. In recent years, **Kurdish girl names** are frequently preferred by parents due to the beauty of their meanings. Here are some of the most loved ones:\n\n* **Zîn:** Means life, the source of life. She is the heroine of the epic Mem û Zîn.\n* **Berfîn:** The name of the snowdrop star. It symbolizes being delicate and stubborn just like a snowdrop.\n* **Evîn:** Means love, affection, and echo. It is one of the most commonly used girl names.\n* **Helîn:** Means bird nest. It represents warmth and affection.\n* **Rojda:** Sunrise, a new day. It is a symbol of a new beginning.\n\n## Unheard Kurdish Girl Names\n\nIf you are looking for deep-meaning **Kurdish girl names** that are not known by everyone, the following options might interest you:\n\n* **Pelşîn:** Means grass, green leaf, spring.\n* **Şîlan:** Means wild rose, rosehip, mountain rose.\n* **Sterk:** Means star, symbolizing brightness and illumination.\n* **Jiyan:** Life, directly meaning life.\n* **Asmîn:** Mountain flower, fresh mountain thyme.\n\nWhen choosing a name, remember that not only the way the name sounds, but also the meaning it carries will leave beautiful marks on your child's life. It is believed that the name you give your child shapes their personality, energy, and future.\n\n## What to Consider When Choosing Kurdish Girl Names?\n\nIf you are choosing a **Kurdish Girl Name**; you can pay attention to the ease of pronunciation, your elders' connection with the name, and of course how pleasant it sounds to your ear. Remember, the important thing is to reach a decision that your whole family embraces. Let's find the most beautiful Kurdish name for the new member of your family. You can easily browse names using the name search and filtering tools on this website.`
  },
  'boys-names-list.json': {
    title: 'Kurdish Boys Names and Meanings (Comprehensive List)',
    desc: 'The most popular, modern, and noble Kurdish boy names. Carefully curated up-to-date Kurdish baby boy names list for expecting parents.',
    content: `Kurdish has many boy names that refer especially to epics, nature, power, and wisdom. **Kurdish boy names** draw attention with their deep meanings and emphatic sound structures. There is no doubt that the name given to your son will be a noble mark he will carry throughout his life.\n\n## The Noblest Kurdish Boy Names\n\nIf you are in search of **Kurdish boy names** inspired by history and the power of nature, here are some wonderful examples frequently used below:\n\n* **Mîr:** Means lord, emir, ruler, and noble leader.\n* **Baran:** Means rain. It symbolizes abundance and vitality.\n* **Şêrko:** Means lion, valiant, and brave person. It represents power.\n* **Cîvan:** Means young, youth.\n* **Diyar:** Means country, hometown, the place lived.\n\n## Kurdish Boy Names Inspired by Nature\n\nKurdish culture has always been intertwined with nature. This is directly reflected in the names:\n\n* **Argeş:** Radiating fire, meaning quite brave.\n* **Aso:** Horizon, dawn, or the furthest field of vision.\n* **Zinar:** Hard rock, mountain peak. A unique depiction of endurance.\n* **Xebat:** Work, effort, labor. It tells of striving in life.\n* **Bager:** Means hurricane, strong wind.\n\nThe naming process is very exciting for every parent. To make your choice correctly, you can browse the entire **Kurdish boy names** archive on our site. When deciding on your son's name, rather than just following the trend of the day, it is always the best idea to look for a meaning he will be proud to carry in his character for a lifetime.`
  },
  'popular-names-list.json': {
    title: 'Most Popular Kurdish Names and Meanings',
    desc: 'The most popular, unique, and modern Kurdish girl names list. Explore meanings and origins to find the ideal name for your child.',
    content: `Are you looking for **Kurdish Girl Names** that are unique, unheard of, and at the same time have deep meanings for your baby girl? Kurdish culture offers wonderful name options through its literature and language, with its broad-rooted structure. We are discussing the concept of **Kurdish girl names**, which parents have shown the most interest in recently, along with the meanings of the names.\n\n## Traditional and Modern Kurdish Girl Names\n\nIn the Kurdish language structure, female names mostly reflect beauty, brightness, nature, flowers, nobility, and goodness. Behind each name, it is seen that it harbors a story or a strong metaphor.\n\nIf your preference is traditional but timeless **Kurdish Girl Names** with very beautiful meanings, you might really like these:\n\n* **Dilşa:** Means cheerful heart, spacious heart, happy woman.\n* **Ronahî:** Means brightness, light, and shine. It is believed that her name will add light to the person for a lifetime.\n* **Bêrîvan:** A nomad milking in the mountains, a hardworking woman. It symbolizes a pure and hardworking culture.\n\nAt the same time, families who prefer modern **Kurdish girl names** that have short and strong pronunciation but still contain very aesthetic meanings can evaluate these alternatives:\n\n* **Lorin:** A very melodic name meaning lullaby, sweet melody.\n* **Arya:** Means noble, aristocratic (The same name is mentioned with noble origin in many states and languages and is a root word in Kurdish).\n* **Viyan:** Represents will, desire, very sincere love.\n\n## The Choice of Expectant Mothers on the Internet\n\nExpectant mothers and fathers frequently search for **Kurdish girl names** and **Kurdish Girl Names** on the internet. To do justice to these intense searches, we host more than 300 unique Kurdish girl names in our database! Using our detailed search engine and Alphabetical name filtering menu, you can easily find the names you want and share them with your expecting friends.\n\nWhen giving your child a gift from **Kurdish girl names**, be careful that it has meanings that will make you happy every time you mention it as a family. We wish her to live with her name!`
  },
  'modern-names-guide.json': {
    title: 'Modern Kurdish Names: Meaningful, Unique, and Latest Baby Names Guide',
    desc: 'The most up-to-date, modern, and meaningful Kurdish baby names guide for 2026. Comprehensive analysis with unique names and origins.',
    content: `The search for **modern Kurdish names** has gained great momentum today. Families prefer names that both protect their cultural ties and adapt to the global world with short, aesthetic pronunciations.\n\n## The Rise of Modern Names\n\nModern names usually consist of 3 or 4 letters. Their pronunciation is easy in every language, and their meanings are usually focused on nature, light, or deep feelings. For example:\n\n* **Alan:** The echo in the mountains.\n* **Sîma:** Face, appearance, visage.\n* **Dara:** Ruler, the one who holds power.\n* **Rana:** Beautiful, pleasant looking.\n\nThese names carry the ancient power of Kurdish while harmonizing with the minimalist trends of modern times. You can explore many more modern names through our **Name Finder** tool.`
  },
  '2026-populer-isimler.json': {
    title: 'The Most Popular Kurdish Baby Names of 2026',
    desc: '2026 is a year where a return to roots and modern tones blend in Kurdish name preferences. In this guide, we review the most popular Kurdish baby names of the year.',
    content: `The year 2026 is a year in Kurdish name preferences where a return to roots and modern tones blend. Mothers and fathers now gravitate towards names that not only sound pleasant but also have a deep story and cultural weight. In this guide, we will review the most preferred names of the year and why these names are so popular.\n\n## Why Did These Names Become a Trend in 2026?\n\nThe biggest factor determining this year's trends are the themes of "nature and freedom". The geographical richness of Mesopotamia, the majesty of the mountains, and the serenity of the rivers come to life in the names of newborn children. In addition, short and concise names that are easy to pronounce in the global world are in the foreground.\n\n## Most Popular Kurdish Girl Names of 2026\n\nElegance, light, and nature-themed names share the summit for baby girls:\n\n* [Arîn](/en/name/arin): (From fire, energetic). It is at the top of the list.\n* [Lîna](/en/name/lina): (Light, sparkle). A highly preferred modern name.\n* [Ronahî](/en/name/ronahi): (Light, brightness).\n\n## Most Popular Kurdish Boy Names of 2026\n\nIn boy names, strong and rooted names stand out:\n\n* [Rênas](/en/name/renas): (Guide, the one who knows the way).\n* [Baran](/en/name/baran): (Rain).\n* [Mîr](/en/name/mir): (Leader, noble).\n\nChoosing a name is leaving a legacy for the future. The Kurdish names trending in 2026 prove how strong this legacy is.`
  },
  'mitolojik-isimler-rehberi.json': {
    title: 'Mythological Kurdish Names: A Legacy from Shahmaran to Kawa',
    desc: 'Legendary baby names from Kurdish mythology. If you want to give your child not just a name but a thousands-of-years-old epic, this guide is for you.',
    content: `Kurdish mythology is full of legends that have glided through the ancient lands of Mesopotamia for thousands of years and reached the present day. The protagonists of these legends still continue to live in the names of newborn babies today. If you want to give your child not just a name, but an epic, this guide is for you.\n\n## The Power of Legends: Why Mythological Names?\n\nMythological names have a character that defies time. These names; represent courage, wisdom, the secrets of nature, and sacrifice. In 2026, with the trend of returning to the roots, interest in these names increased by 40%.\n\n## Prominent Mythological Names and Their Stories\n\n* [Kawa](/en/name/kawa): The most known hero of Kurdish mythology. The blacksmith Kawa, who lit the fire of rebellion against the cruel Dehak, is the symbol of freedom and resistance. The name Kawa represents a strong will.\n* **Şahmaran**: The queen of snakes. It is the symbol of wisdom, healing, and eternal love. It is preferred as an extremely powerful and mystical girl name.\n* **Sîmir**: (Simurgh) The legendary phoenix. It represents rebirth from ashes and eternal life.\n* **Rostem**: The invincible warrior of the epic. It is the absolute symbol of power and courage.\n\nMythological names carry the magic of the past to the future.`
  },
  'modern-ve-nadir-isimler.json': {
    title: 'Modern and Rare Kurdish Names: Hidden Treasures',
    desc: 'Unique, unheard of, modern and meaningful Kurdish baby names. A special guide full of elegant and strong names like Rênas and Arîn.',
    content: `The biggest excitement parents experience when choosing a name for their baby is the search for a name that is both **meaningful** and **unique**. The weight of classic names is always different, but in the modern world, rare Kurdish names that are easier to pronounce, aesthetic, and unheard of are also in a huge upward trend.\n\nIf you want your child to be noticed immediately with their name in crowds, you should definitely check out these hidden treasures.\n\n## Why Modern and Rare Names?\n\nKurdish is a highly musical and poetic language due to its phonetic structure. Modern names usually offer a **short and concise** syllable structure, inspired by nature, love, or philosophical concepts. Thus, it both keeps up with the speed of the modern world and refers to an ancient past.\n\n## The Most Beautiful Modern Kurdish Baby Names\n\nIn this list, we have compiled a few of those unique names that have been on the rise in recent years but have not yet been fully discovered:\n\n*   [Arîn](/en/name/arin): (Girl/Unisex) Meaning coming from fire, energetic and sparkly like fire.\n*   [Rênas](/en/name/renas): (Boy) Means the one who knows the way, guide, wise person.\n*   [Lîna](/en/name/lina): (Girl) Meaning a small dewdrop, which is one of the fine details of nature, it also represents elegance in some regions.\n*   [Pêl](/en/name/pel): (Girl/Boy) Wave. It is a very strong 3-letter name that contains the power of both a raging and calm sea.\n*   [Jêhat](/en/name/jehat): (Boy) Means talented, skillful, hardworking.\n\n## Tips When Making a Selection\n\nThe most important point to consider when choosing rare names is the harmony of the name's **spelling and pronunciation**. Modern Kurdish names usually meet this rule perfectly.\n\nUsing the **Name Finder** tool on our site, you can discover more [Hidden Treasure](/en) names according to the starting letter or theme you are looking for, and make the right choice for your baby.`
  }
};

for (const [filename, contentObj] of Object.entries(posts)) {
  const filePath = path.join(enDir, filename);
  fs.writeFileSync(filePath, JSON.stringify(contentObj, null, 2), 'utf8');
}
console.log('Successfully created English blog posts.');
